export const tickerItems = [
    { src: "/tickerLogos/m-s.webp", alt: "Car Brand Logo" },
    { src: "/tickerLogos/f-i.webp", alt: "Car Brand Logo" },
    { src: "/tickerLogos/c-c.webp", alt: "Car Brand Logo" },
    { src: "/tickerLogos/c-n.webp", alt: "Car Brand Logo" },
    { src: "/tickerLogos/t-a2.webp", alt: "Car Brand Logo" },
    { src: "/tickerLogos/b-w.webp", alt: "Car Brand Logo" },
    { src: "/tickerLogos/h-i.webp", alt: "Car Brand Logo" },
    { src: "/tickerLogos/j-r.webp", alt: "Car Brand Logo" },
    { src: "/tickerLogos/s-i.webp", alt: "Car Brand Logo" },
    { src: "/tickerLogos/p-e.webp", alt: "Car Brand Logo" },
    { src: "/tickerLogos/s-u.webp", alt: "Car Brand Logo" },
    { src: "/tickerLogos/r-t.webp", alt: "Car Brand Logo" },
    { src: "/tickerLogos/c-t.webp", alt: "Car Brand Logo" },
    { src: "/tickerLogos/l-i.webp", alt: "Car Brand Logo" },
    { src: "/tickerLogos/p-t.webp", alt: "Car Brand Logo" },
    { src: "/tickerLogos/k-g.webp", alt: "Car Brand Logo" },
    { src: "/tickerLogos/r-r.webp", alt: "Car Brand Logo" },
    { src: "/tickerLogos/m-a.webp", alt: "Car Brand Logo" },
    { src: "/tickerLogos/s-a.webp", alt: "Car Brand Logo" },
    { src: "/tickerLogos/t-a.webp", alt: "Car Brand Logo" },
];